// Template definitions for VideMove
// Each template defines: colors, fonts, overlay style, subtitle style, border, platform

export const TEMPLATES = {
  neonDark: {
    id: 'neonDark',
    name: 'Neon Dark',
    description: 'Dark background with electric neon accents',
    platform: ['TikTok', 'Reels', 'Shorts'],
    colors: {
      background: '#000000',
      primary: '#00f5ff',
      secondary: '#ff00ff',
      text: '#ffffff',
      textShadow: '#00f5ff',
      subtitleBg: 'rgba(0, 0, 0, 0.85)',
      subtitleText: '#ffffff',
      subtitleBorder: '#00f5ff',
    },
    overlay: {
      type: 'gradient',
      gradient: 'linear-gradient(0deg, rgba(0,0,0,0.8) 0%, transparent 40%, transparent 70%, rgba(0,0,0,0.4) 100%)',
    },
    title: {
      position: 'bottom',
      fontSize: 42,
      fontWeight: '900',
      fontFamily: 'Outfit',
      textTransform: 'uppercase',
      letterSpacing: '2px',
      glow: true,
    },
    subtitle: {
      position: 'bottom-center',
      fontSize: 18,
      padding: '6px 16px',
      borderRadius: 4,
      borderLeft: '3px solid #00f5ff',
    },
    border: {
      type: 'neon',
      color: '#00f5ff',
      width: 3,
    },
    preview: { bg: 'linear-gradient(135deg, #000 60%, #001a1a 100%)', accent: '#00f5ff' },
  },

  cleanWhite: {
    id: 'cleanWhite',
    name: 'Clean White',
    description: 'Minimal light design for professional content',
    platform: ['YouTube', 'LinkedIn'],
    colors: {
      background: '#ffffff',
      primary: '#1a1a2e',
      secondary: '#4f46e5',
      text: '#ffffff',
      textShadow: 'rgba(0,0,0,0.5)',
      subtitleBg: 'rgba(255, 255, 255, 0.92)',
      subtitleText: '#1a1a2e',
      subtitleBorder: '#4f46e5',
    },
    overlay: {
      type: 'gradient',
      gradient: 'linear-gradient(0deg, rgba(26,26,46,0.85) 0%, transparent 45%)',
    },
    title: {
      position: 'bottom',
      fontSize: 36,
      fontWeight: '700',
      fontFamily: 'Inter',
      textTransform: 'none',
      letterSpacing: '0px',
      glow: false,
    },
    subtitle: {
      position: 'bottom-center',
      fontSize: 16,
      padding: '5px 14px',
      borderRadius: 6,
      borderLeft: 'none',
    },
    border: {
      type: 'none',
    },
    preview: { bg: 'linear-gradient(135deg, #f8f9ff 0%, #e8e8ff 100%)', accent: '#4f46e5' },
  },

  gradientPop: {
    id: 'gradientPop',
    name: 'Gradient Pop',
    description: 'Vibrant gradient perfect for Instagram Stories',
    platform: ['Instagram', 'Stories', 'Reels'],
    colors: {
      background: '#ff6b6b',
      primary: '#ffd93d',
      secondary: '#ff6b6b',
      text: '#ffffff',
      textShadow: 'rgba(0,0,0,0.4)',
      subtitleBg: 'rgba(255, 255, 255, 0.2)',
      subtitleText: '#ffffff',
      subtitleBorder: 'rgba(255,255,255,0.6)',
    },
    overlay: {
      type: 'gradient',
      gradient: 'linear-gradient(135deg, rgba(255,107,107,0.3) 0%, rgba(78,205,196,0.2) 100%)',
    },
    title: {
      position: 'center',
      fontSize: 48,
      fontWeight: '900',
      fontFamily: 'Outfit',
      textTransform: 'uppercase',
      letterSpacing: '3px',
      glow: false,
    },
    subtitle: {
      position: 'bottom-center',
      fontSize: 18,
      padding: '8px 20px',
      borderRadius: 25,
      borderLeft: 'none',
    },
    border: {
      type: 'animated',
      color: 'linear-gradient(90deg, #ffd93d, #ff6b6b, #a855f7, #22d3ee, #ffd93d)',
      width: 4,
    },
    preview: { bg: 'linear-gradient(135deg, #ff6b6b 0%, #ffd93d 50%, #4ecdc4 100%)', accent: '#ffffff' },
  },

  cinematic: {
    id: 'cinematic',
    name: 'Cinematic',
    description: 'Film-style with letterbox bars for YouTube',
    platform: ['YouTube', 'Facebook'],
    colors: {
      background: '#000000',
      primary: '#c8a96e',
      secondary: '#8b6914',
      text: '#f5e6c8',
      textShadow: 'rgba(0,0,0,0.8)',
      subtitleBg: 'rgba(0, 0, 0, 0.0)',
      subtitleText: '#f5e6c8',
      subtitleBorder: 'transparent',
    },
    overlay: {
      type: 'letterbox',
      gradient: 'linear-gradient(0deg, rgba(0,0,0,0.6) 0%, transparent 20%, transparent 80%, rgba(0,0,0,0.6) 100%)',
    },
    title: {
      position: 'bottom',
      fontSize: 32,
      fontWeight: '600',
      fontFamily: 'Outfit',
      textTransform: 'none',
      letterSpacing: '4px',
      glow: false,
    },
    subtitle: {
      position: 'bottom-center',
      fontSize: 17,
      padding: '4px 12px',
      borderRadius: 0,
      borderLeft: 'none',
    },
    border: {
      type: 'letterbox',
      color: '#000000',
      barHeight: 80,
    },
    preview: { bg: 'linear-gradient(180deg, #000 0%, #1a1200 50%, #000 100%)', accent: '#c8a96e' },
  },

  boldPromo: {
    id: 'boldPromo',
    name: 'Bold Promo',
    description: 'Strong CTA design for Facebook & YouTube ads',
    platform: ['Facebook', 'YouTube', 'Ads'],
    colors: {
      background: '#0f0f23',
      primary: '#ff4444',
      secondary: '#ff8800',
      text: '#ffffff',
      textShadow: 'rgba(0,0,0,0.8)',
      subtitleBg: 'rgba(255, 68, 68, 0.9)',
      subtitleText: '#ffffff',
      subtitleBorder: 'transparent',
    },
    overlay: {
      type: 'gradient',
      gradient: 'linear-gradient(0deg, rgba(15,15,35,0.9) 0%, transparent 35%, transparent 75%, rgba(15,15,35,0.5) 100%)',
    },
    title: {
      position: 'bottom',
      fontSize: 40,
      fontWeight: '900',
      fontFamily: 'Outfit',
      textTransform: 'uppercase',
      letterSpacing: '1px',
      glow: false,
    },
    subtitle: {
      position: 'bottom-center',
      fontSize: 16,
      padding: '5px 16px',
      borderRadius: 4,
      borderLeft: 'none',
    },
    border: {
      type: 'strip',
      color: 'linear-gradient(90deg, #ff4444, #ff8800)',
      stripHeight: 6,
    },
    preview: { bg: 'linear-gradient(135deg, #0f0f23 0%, #1a0a0a 100%)', accent: '#ff4444' },
  },
};
